apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: infoportal
  name: infoportal-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infoportal-api
  template:
    metadata:
      labels:
        app: infoportal-api
    spec:
      containers:
      - name: app
        image: infoportal-api:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: infoportal-config
        - secretRef:
            name: infoportal-secret
        volumeMounts:
        - name: app-data
          mountPath: /app/data
      volumes:
      - name: app-data
        persistentVolumeClaim:
          claimName: app-data-pvc
