apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: infoportal
  name: whatsapp-data-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
