---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boinc
  namespace: boinc
  labels:
    app: boinc
spec:
  replicas: 1
  template:
    metadata:
      name: boinc
      namespace: boinc
      labels:
        app: boinc
    spec:
      containers:
        - name: boinc
          image: boinc/client
          imagePullPolicy: Always
          env:
            - name: TZ
              value: "America/New_York"
            - name: BOINC_GUI_RPC_PASSWORD
              value: "123"
            - name: BOINC_CMD_LINE_OPTIONS
              value: "--allow_remote_gui_rpc"
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
            - containerPort: 443
              name: https
              protocol: TCP
            - containerPort: 31416
              name: manager
              protocol: TCP
  selector:
    matchLabels:
      app: boinc
