---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: boinc-pvc
  namespace: boinc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
