apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: jenkins.lab.qstetten.de
    http:
      paths:
      - backend:
          service:
            name: external-service-jenkins
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - jenkins.lab.qstetten.de
    secretName: jenkins-cert
