apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxy-ingress
  namespace: proxy
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - proxy.lab.qstetten.de
      secretName: proxy-qstetten-cert
  rules:
    - host: "proxy.lab.qstetten.de"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: mitmproxy
                port:
                  number: 80