apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: snake
spec:
  rules:
    - host: snake.lab.qstetten.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: snake
                port:
                  number: 80