apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch-operator
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: opensearch
  project: default
  sources:
    - chart: opensearch-operator
      repoURL: https://opensearch-project.github.io/opensearch-k8s-operator/
      targetRevision: 2.6.0
      helm:
        valueFiles:
          - $opensearch/opensearch/operator/values.yml
    - repoURL: https://github.com/lsgadminlab/argo-k8s-resources/
      targetRevision: HEAD
      path: opensearch
      ref: opensearch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
